"""add jsonb_data to plan

Revision ID: 01d4dff42c09
Revises: 782a0adb3ed7
Create Date: 2026-02-20 13:45:15.216580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01d4dff42c09'
down_revision: Union[str, Sequence[str], None] = '782a0adb3ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('jsonb_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'jsonb_data')
    # ### end Alembic commands ###
