"""name for plan

Revision ID: e13b7eeb7efb
Revises: f23d1a6112ad
Create Date: 2026-02-20 18:39:13.850948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e13b7eeb7efb'
down_revision: Union[str, Sequence[str], None] = 'f23d1a6112ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_column('plans', 'name')
    # ### end Alembic commands ###
