"""refactor rider table

Revision ID: f23d1a6112ad
Revises: 01d4dff42c09
Create Date: 2026-02-20 15:59:24.316442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23d1a6112ad'
down_revision: Union[str, Sequence[str], None] = '01d4dff42c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riders', sa.Column('rider_json', sa.JSON(), nullable=False))
    op.drop_column('riders', 'price')
    op.drop_column('riders', 'rider_name')
    op.drop_column('riders', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riders', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('riders', sa.Column('rider_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('riders', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('riders', 'rider_json')
    # ### end Alembic commands ###
